const actions = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_WINDOW_SIZE: "SET_WINDOW_SIZE",
  SET_RECORD: "SET_RECORD",
  SET_STOP_RECORD: "SET_STOP_RECORD",
  SET_CLEAR_RECORD: "SET_CLEAR_RECORD",
  SET_PLAY_RECORD: "SET_PLAY_RECORD",
};
export default actions;
